services:
    # Autowire alias
    BestIt\CommercetoolsODM\Filter\FilterManagerInterface: '@best_it.commercetools_odm.filter.filter_manager'
    BestIt\CommercetoolsODM\DocumentManagerInterface: '@best_it.commercetools_odm.manager'

    best_it.commercetools_odm.action_builder.factory.default:
        class: BestIt\CommercetoolsODM\ActionBuilder\ActionBuilderFactory
        arguments: ['@cache.system']

    best_it.commercetools_odm.action_builder.processor.default:
        class: BestIt\CommercetoolsODM\ActionBuilder\ActionBuilderComposite
        arguments: ['@best_it.commercetools_odm.action_builder.factory']

    best_it.commercetools_odm.class_metadata_factory.default:
        class: BestIt\CommercetoolsODM\Mapping\ClassMetadataFactory
        public: false
        arguments:
            - '@best_it.commercetools_odm.mapping.annotations.driver'

    best_it.commercetools_odm.event_manager.default:
        class: Doctrine\Common\EventManager
        public: false

    best_it.commercetools_odm.filter.filter_manager:
        class: BestIt\CommercetoolsODM\Filter\FilterManager

    best_it.commercetools_odm.listener_invoker.default:
        arguments: ['@best_it.commercetools_odm.event_manager']
        class: BestIt\CommercetoolsODM\Event\ListenersInvoker
        public: false

    best_it.commercetools_odm.manager:
        class: BestIt\CommercetoolsODM\DocumentManager
        arguments:
            - '@best_it.commercetools_odm.class_metadata_factory'
            - '@best_it.commercetools_odm.client'
            - '@best_it.commercetools_odm.query_helper'
            - '@best_it.commercetools_odm.repository_factory'
            - '@best_it.commercetools_odm.unit_of_work.factory'
        calls:
            - [setLogger, ['@?best_it.commercetools_odm.logger']]

    best_it.commercetools_odm.mapping.annotations.driver.default:
        class: BestIt\CommercetoolsODM\Mapping\Driver\AnnotationDriver
        arguments: [ '@annotation_reader' ]

    best_it.commercetools_odm.query_helper.default:
        class: Commercetools\Commons\Helper\QueryHelper

    best_it.commercetools_odm.repository_factory.default:
        class: BestIt\CommercetoolsODM\RepositoryFactory
        arguments:
            - '@best_it.commercetools_odm.filter.filter_manager'
            - '@?best_it.commercetools_odm.request_pool'
        public: false

    best_it.commrecetools_odm.unit_of_work.factory.default:
        class: BestIt\CommercetoolsODM\UnitOfWorkFactory
        public: false
        arguments:
            - '@best_it.commercetools_odm.action_builder.processor'
            - '@best_it.commercetools_odm.event_manager'
            - '@best_it.commercetools_odm.listener_invoker'
        calls:
            - [setLogger, ['@?best_it.commercetools_odm.logger']]
